package com.streetfix.enums;

public enum Role {
    ROLE_CITIZEN,
    ROLE_WORKER,
    ROLE_OFFICER,
    ROLE_WARD_SUPERVISOR,
    ROLE_ASSISTANT_COMMISSIONER,
    ROLE_ZONAL_OFFICER,
    ROLE_MUNICIPAL_COMMISSIONER,
    ROLE_ADMIN,
    ROLE_SUPER_ADMIN
}
